//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.ibm.ivr.eus.websrv.belk;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xPrintOverNightReportsReturn" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xPrintOverNightReportsReturn"
})
@XmlRootElement(name = "xPrintOverNightReportsResponse")
public class XPrintOverNightReportsResponse {

    @XmlElement(required = true, nillable = true)
    protected String xPrintOverNightReportsReturn;

    /**
     * Gets the value of the xPrintOverNightReportsReturn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPrintOverNightReportsReturn() {
        return xPrintOverNightReportsReturn;
    }

    /**
     * Sets the value of the xPrintOverNightReportsReturn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPrintOverNightReportsReturn(String value) {
        this.xPrintOverNightReportsReturn = value;
    }
}