//
// Generated By:JAX-WS RI IBM 2.1.6 in JDK 6 (JAXB RI IBM JAXB 2.1.10 in JDK 6)
//

package com.ibm.ivr.eus.websrv.belk;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="xPrinterName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xReportsToPrint" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "xPrinterName",
    "xReportsToPrint"
})
@XmlRootElement(name = "xPrintOverNightReports")
public class XPrintOverNightReports {

    @XmlElement(required = true, nillable = true)
    protected String xPrinterName;
    @XmlElement(required = true, nillable = true)
    protected String xReportsToPrint;

    /**
     * Gets the value of the xPrinterName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXPrinterName() {
        return xPrinterName;
    }

    /**
     * Sets the value of the xPrinterName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXPrinterName(String value) {
        this.xPrinterName = value;
    }

    /**
     * Gets the value of the xReportsToPrint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXReportsToPrint() {
        return xReportsToPrint;
    }

    /**
     * Sets the value of the xReportsToPrint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXReportsToPrint(String value) {
        this.xReportsToPrint = value;
    }
}